# Generated by Django 2.1 on 2019-11-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Artist Name')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('facebook', models.TextField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.TextField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.TextField(blank=True, null=True, verbose_name='Instagram')),
                ('youtube', models.TextField(blank=True, null=True, verbose_name='Instagram')),
                ('mediaKitLink', models.TextField(blank=True, null=True, verbose_name='Instagram')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'artist',
                'verbose_name_plural': 'artists',
            },
        ),
    ]
