# Generated by Django 2.2.6 on 2019-11-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20191104_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='short_description',
            field=models.CharField(default='Hello', max_length=50, verbose_name='Short Description'),
            preserve_default=False,
        ),
    ]
